@startuml

' --------------------------------------------------- references -----

' https://www.augmentedmind.de/2021/01/17/plantuml-layout-tutorial-styles/

' ----------------------------------------------------- settings -----

skinparam defaultFontSize 10

' square lines
skinparam linetype ortho

' handwritten
skinparam handwritten true

' direction
'top to bottom direction
'left to right direction

' ------------------------------------------------------ example -----

' shape "room name" as 50(land level)_1000(roomnumber)
' rectangle "example" as 50_1000
' rectangle "two line \n example" as 51_1000
' 50_0001 -l- 51_0003
' 50_0001 -r- 51_0004

frame "old cathedral" {

' ----------------------------------------------------- level +2 -----

package "level +2" {

rectangle "ack! bats in my \n belfry!" as 52_0001

' ack! bats in my belfry!

}

' ----------------------------------------------------- level +1 -----

package "level +1" {

rectangle "climbing the bell \n tower" as 51_0001
rectangle "the priest's \n retreat" as 51_0002

' climbing the bell tower
51_0001 -u- 51_0002

}

' ----------------------------------------------------- level +0 -----

package "level +0" {

rectangle "forgotten path \n (enter)" as 50_0001
rectangle "before an old \n cathedral" as 50_0002
rectangle "antechamber" as 50_0003
rectangle "assemblage" as 50_0004
rectangle "confessional" as 50_0005
rectangle "small meeting \n room" as 50_0006
rectangle "front of \n assemblage" as 50_0007
rectangle "front of \n assemblage" as 50_0008
rectangle "front of \n assemblage" as 50_0009
rectangle "raised altar" as 50_0010
rectangle "darkened \n stairwell" as 50_0011
rectangle "priest's chamber" as 50_0012

' forgotten path
50_0001 -u- 50_0002

' before an old cathedral
50_0002 -u- 50_0003

' antechamber
50_0003 -u- 50_0004

' assemblage
50_0004 -u- 50_0007
50_0004 -l- 50_0005
50_0004 -r- 50_0006

' front of assemblage
50_0007 -u- 50_0010
50_0007 -l- 50_0008
50_0007 -r- 50_0009

' raised altar
50_0010 -l- 50_0011
50_0010 -r- 50_0012

}

' ----------------------------------------------------- level -1 -----

package "level -1" {

rectangle "storage room" as 49_0001
rectangle "old hallway" as 49_0002
rectangle "ancient tomb" as 49_0003
rectangle "ancient tomb" as 49_0004
rectangle "old hallway" as 49_0005
rectangle "char's tomb" as 49_0006
rectangle "kyn's tomb" as 49_0007
rectangle "hole in the foundation" as 49_0008

' storage room
49_0001 -d- 49_0002

' old hallway
49_0002 -l- 49_0003
49_0002 -r- 49_0004
49_0002 -d- 49_0005

' old hallway
49_0005 -l- 49_0006
49_0005 -r- 49_0007
49_0005 -d- 49_0008

}

' ------------------------------------------------------- stairs -----

' climbing the bell tower ->  ack! bats in my belfry!
51_0001 .r.> 52_0001 : up

' antechamber -> climbing the bell tower
50_0003 .r.> 51_0001 : up

' darkened stairwell -> storage room
50_0011 .l.> 49_0001 : down

}

@enduml
