@startuml

skinparam defaultFontSize 10

rectangle "on the southern part \n of the balcony" as 0001
rectangle "stairs to the balcony" as 0002
rectangle "south western corner \n of the balcony" as 0003
rectangle "south eastern corner \n of the balcony" as 0004

0002 -u- 0001

0001 -l- 0003
0001 -r- 0004

@enduml
